baseURL = 'https://vincat.github.io'
languageCode = 'en-au'
title = 'My Homelab Notes'
theme = 'hugo-theme-relearn-5.24.1'

[params]
subtitle = 'Homelab learning and experiments'
author.name = "Vincent Cox"
description = "Documentation for Hugo Relearn Theme"
# For search functionality
[outputs]
home = [ "html", "rss", "search"]

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"

[[menu.shortcuts]]
name = "<i class='fas fa-layer-group'></i> Categories"
url = "/categories"
