baseURL = 'https://vincat.github.io'
languageCode = 'en-au'
title = 'My Homelab Notes'
theme = 'hugo-theme-relearn-5.24.1'
enableEmoji = true
collapsibleMenu = true

[params]
subtitle = 'Homelab learning and experiments'
author.name = "Vincent Cox"
description = "Documentation for my Homelab"
# For search functionality
[outputs]
home = [ "html", "rss", "search"]

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"

[[menu.shortcuts]]
name = "<i class='fas fa-layer-group'></i> Categories"
url = "/categories"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[markup.goldmark.renderer]
    unsafe = true

[[params.themeVariant]]
    identifier = 'zen-dark'

